### ISSUE TITLE
SignalR-Client-Cpp in release mode asks for cpprest140d_2_6.dll

### ISSUE THREAD

**Issue by nicolasr75** [aspnet/SignalR-Client-Cpp#127]
I am testing with Visual Studio 2015 and the nuget package for SignalR-Client-Cpp.
Installing the package also installs Cpp Rest as expected. Running my test application in debug mode works fine. However, when I switch to release mode I get an error for a missing Cpp Rest debug DLL (cpprest140d_2_6.dll). Is this a problem of the nuget package?

**Comment by moozzyk** [comment]
Are you installing this package http://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop/1.0.0-alpha1? I think the issue might be that this package is meant to be used with the compiler that was included in VS2013 and not VS2015. I am actually a bit surprised things worked when compiling the Debug version with VS2015 - last time I tried it did not work.
I did make necessary changes and the client now compiles with VS2015 however the package has not been shipped yet. You can however create the package on your machine - from VS 2015 command prompt run `msbuild /t:CreatePackage /p:Configuration=Release /p:Platform=x64` (Configuration and Platform are optional and default to `Debug` and `Win32` respectively). Once you have a package you can copy it to local folder and add this folder as a NuGet source. This way you will be able to install the package easily to your project.

**Comment by nicolasr75** [comment]
I was using the package from the https://www.myget.org/F/aspnetvnext/ feed:
Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop
OK, I will try to build it myself. Thanks.

**Comment by nicolasr75** [comment]
Sorry, I think I don't quite get it. I downloaded the entire source tree to a local directory, started the VS2015 command prompt, changed to the solution directory and ran:
c:\MyDir>msbuild signalrclient.sln /t:signalrclientdll /p:Configuration=Release /p:Platform=x64
The build works fine but how is the nuget package supposed to be created and where? Is this an extra step? Thanks Nicolas

**Comment by moozzyk** [comment]
If you are using the Microsoft.AspNet.SignalR.Client.Cpp.v140.WinDesktop package then you don't need to build your own package - this is the version for VS2015 (v140 indicates toolset used in VS2015) but it was not yet published to NuGet.  and there must be something wrong with the targets file. I will look into this. 
I just noticed that the build command I provided was missing the project file which was probably the reason why you couldn't make it work. It should have been `msbuild build\build.msbuild /t:CreatePackage /p:Configuration=Release /p:Platform=x64` (you run it from the project root folder). As I said - you don't need to build the package on your own since you are using the correct one and the bug appears to be somewhere in one of the targets file.

**Comment by nicolasr75** [comment]
Just out of curiosity I built the package myself using your command and created a local nuget feed. With this package I don't experience the problem. I did not change anything in the targets file!

**Comment by woodmeister123** [comment]
I have the same issue, running dependency walker on the package currently on nuget.org (VS2013), the release dll appears to depend on the debug version of the rest dll.

**Comment by moozzyk** [comment]
@woodmeister123 - I just checked and I don't see this. For the package on NuGet Debug version depend on Debug version of Casablanca but Release versions depend on Release version of casablanca:

```
PS C:\Source\SignalR> dumpbin /dependents "C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\x64\v120\Debug\signalrclient.dll"
Microsoft (R) COFF/PE Dumper Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\x64\v120\Debug\signalrclient.dll

File Type: DLL

  Image has the following dependencies:

    cpprest120d_2_5.dll
    KERNEL32.dll
    MSVCP120D.dll
    MSVCR120D.dll

  Summary

       10000 .data
       16000 .pdata
       6F000 .rdata
        3000 .reloc
        1000 .rsrc
       EF000 .text
PS C:\Source\SignalR> dumpbin /dependents "C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\Win32\v120\Debug\signalrclient.dll"
Microsoft (R) COFF/PE Dumper Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\Win32\v120\Debug\signalrclient.dll

File Type: DLL

  Image has the following dependencies:

    cpprest120d_2_5.dll
    KERNEL32.dll
    MSVCP120D.dll
    MSVCR120D.dll

  Summary

        F000 .data
       24000 .rdata
        A000 .reloc
        1000 .rsrc
       BB000 .text

PS C:\Source\SignalR> dumpbin /dependents "C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\x64\v120\Release\signalrclient.dll"
Microsoft (R) COFF/PE Dumper Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\x64\v120\Release\signalrclient.dll

File Type: DLL

  Image has the following dependencies:

    cpprest120_2_5.dll
    KERNEL32.dll
    MSVCP120.dll
    MSVCR120.dll

  Summary

       10000 .data
        7000 .pdata
       34000 .rdata
        2000 .reloc
        1000 .rsrc
       58000 .text
PS C:\Source\SignalR> dumpbin /dependents "C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\Win32\v120\Release\signalrclient.dll"
Microsoft (R) COFF/PE Dumper Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\Temp\SignalRCpp\microsoft.aspnet.signalr.client.cpp.v120.windesktop.1.0.0-alpha1.nupkg\build\native\dll\Win32\v120\Release\signalrclient.dll

File Type: DLL

  Image has the following dependencies:

    cpprest120_2_5.dll
    KERNEL32.dll
    MSVCP120.dll
    MSVCR120.dll

  Summary

        F000 .data
       18000 .rdata
        7000 .reloc
        1000 .rsrc
       54000 .text
```

**Comment by moozzyk** [comment]
This is fixed. The packages on nightly feed have now correct dependencies.
