### ISSUE TITLE
connection_impl serializes string twice when payload is string

### ISSUE THREAD

**Issue by jcabot21** [aspnet/SignalR-Client-Cpp#128]
**connection_impl::process_response** parses the string_t response parameter and calls **invoke_message_received** for each node received which calls the message received callback after serializing the payload. I'm seeing that this works correctly in all cases except when the node is already a string. When the payload is already a string special characters are double escaped, which means if later on you want to use the string as a json you have to parse it twice.

This doesn't seem like correct behavior. If it is incorrect it could be avoided by retrieving the string with the use of **as_string** instead of serializing.

**Comment by moozzyk** [comment]
Thanks for reporting this. This is a bug indeed.

**Comment by moozzyk** [comment]
Fixed in 2410a499fb0daf60be1cdbd01a69b3abf5a57fc1
