### ISSUE TITLE
"exception when starting or stopping connection: WebSockets not supported on the server and there is no fallback transport"

### ISSUE THREAD

**Issue by MyPCIsBetter** [aspnet/SignalR-Client-Cpp#130]
My server: asp.NET c# application. Runs on Microsoft Azure.
As far as I know Server-side SignalR supports WebSockets. What is the problem then?
Strange thing is: when I tested in on my local server (so, basically the same code, but runned on local computer) everything worked, but when I moved it to Azure, this error stared to appear.
Can I somehow enforce WebSocket connection (like it is in javascript version of signalr)?

**Comment by moozzyk** [comment]
AFAIR websockets are disabled by default on Azure. You need to turn it on.
