### ISSUE TITLE
hub_connection.h uses the U macro instead of _XPLATSTR

### ISSUE THREAD

**Issue by VincentLascaux** [aspnet/SignalR-Client-Cpp#137]
Because hub_connection.h uses the U macro, SignalR client can't be compiled with _TURN_OFF_PLATFORM_STRING.
I think U should be replaced with _XPLATSTR in the public headers

**Comment by moozzyk** [comment]
Thanks for reporting this.

**Comment by moozzyk** [comment]
Fixed in 9cd0db8ae2425b8c2ac377f3db3e5425458d5d0c
