### ISSUE TITLE
Unable to build solution

### ISSUE THREAD

**Issue by khuramshahzad** [aspnet/SignalR-Client-Cpp#138]
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project PersistentConnectionSample: Unable to find version '1.0.0-alpha-10017' of package 'Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop'.
  https://api.nuget.org/v3/index.json: Package 'Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop.1.0.0-alpha-10017' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.myget.org/F/aspnetrelease/api/v3/index.json: Package 'Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop.1.0.0-alpha-10017' is not found on source 'https://www.myget.org/F/aspnetrelease/api/v3/index.json'.
  https://www.myget.org/F/aspnetrelease/: Package 'Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop.1.0.0-alpha-10017' is not found on source 'https://www.myget.org/F/aspnetrelease/'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'Microsoft.AspNet.SignalR.Client.Cpp.v120.WinDesktop.1.0.0-alpha-10017' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
.			0

**Comment by moozzyk** [comment]
Probably the old version was removed from the feed. Try using moving to beta. The latest version on the aspnetrelease feed is: v1.0.0-beta1-15004. In the future you can check the latest version here: https://myget.org/gallery/aspnetrelease.
