### ISSUE TITLE
Support fallback to Long Polling and Server Sent Events

### ISSUE THREAD

**Issue by Sonic78** [aspnet/SignalR-Client-Cpp#139]
Currently I couldn't find and documentation, readme etc. that describes if fallback to  Long Polling and/or Server Sent Events are supported by this C++ client. Checking other tickets let me assume that currently the SignalR-Client-Cpp dosen't provide the essential fallback to Long Polling and/or Server Sent Events when WebSockets are not supported by the server or blocked by a firewall.
Please implement at least one fallback and somewhere document this limitation.

**Comment by moozzyk** [comment]
You are correct. Currently the only supported transport is websockets. This is tracked here: https://github.com/aspnet/SignalR-Client-Cpp/issues/62 so I will close this issue as a duplicate.
