### ISSUE TITLE
websocket_transport::disconnect could call m_receive_loop_cts.cancel() during assignment

### ISSUE THREAD

**Issue by halter73** [aspnet/SignalR-Client-Cpp#70]
The `m_receive_loop_cts = receive_loop_cts;` line in `websocket_transport::connect` seems to temporarily clear the cts pimpl. If `m_receive_loop_cts.cancel()` is called during the assignment, this might lead to an attempted null pointer dereference.

**Comment by moozzyk** [comment]
Fixed as part of reconnect work e41a8ff - the assignment is now being done in a lock
